version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: mydoses-postgres
    restart: always
    environment:
      POSTGRES_USER: mydoses
      POSTGRES_PASSWORD: mydoses-password
      POSTGRES_DB: mydoses_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
#postgres://mydoses:mydoses-password@localhost:5432/mydoses_db